name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on semver tags like v0.1.0, v1.2.3

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: GoReleaser
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}